# Generated by Django 4.2.9 on 2024-04-16 12:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Location',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(default='Unknown location', max_length=50)),
        #         ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
        #     ],
        # ),
    ]
