# Generated by Django 4.2.9 on 2024-04-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_location'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Location',
        # ),
    ]
