# Generated by Django 4.2.9 on 2024-05-10 11:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown location', max_length=50)),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
