# Generated by Django 4.2.9 on 2024-06-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cover_refined',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
